# Generated by Django 3.2.4 on 2021-06-25 17:30

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_bio', ckeditor.fields.RichTextField(max_length=200, null=True)),
                ('bio', ckeditor.fields.RichTextField(max_length=500, null=True)),
                ('profile_pic', models.ImageField(default='default-profile-pic.jpeg', upload_to='profiles-pics')),
                ('twitter', models.CharField(blank=True, default='@', help_text="Enter just your handle, example, '@superbob'.", max_length=255)),
                ('youtube', models.CharField(blank=True, help_text="Enter just your username, example, 'bobbarker'.", max_length=255)),
                ('linkedin', models.CharField(blank=True, help_text="Enter just your username, example, 'bobbarker'.", max_length=255)),
                ('instagram', models.CharField(blank=True, default='@', help_text="Enter just your handle, example, '@superbob'.", max_length=255)),
                ('github', models.CharField(blank=True, help_text="Enter just your username, example, 'superbob'.", max_length=255)),
                ('author_website', models.CharField(blank=True, default='https://', help_text='Enter your full website URL, eg. https://youwebsite.com ', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('header_image', models.ImageField(upload_to='blog/%Y/%m/%d')),
                ('header_image_alt', models.CharField(default="Sorry, we're assholes and forgot to give you an image description.", max_length=200)),
                ('post_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('intro', ckeditor.fields.RichTextField(max_length=160)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('meta_description', models.TextField(default='meta description', max_length=160)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category')),
            ],
        ),
    ]
